title: Naijia Jin # your name (or website title) here
logo: "/images/me.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Candidates of Entertainment Technology Center in Carnegie Mellon University 
  <br><br>
  programmer, technical artist, game designer 
  <br><br>
  <a href="linkedin.com/in/naijia-jin-b33b45190">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
